enum Strings {
    allRightsReserved = '© 2020 AtomicLabs. Todos los derechos reservados.',
    conquer = 'CONQUISTA',
    continue = 'Continuar',
    explore = 'EXPLORA',
    firstNameError = 'El nombre deberá tener mínimo 5 caracteres',
    imagine = 'IMAGINA',
    lastNameError = 'El apellido deberá tener mínimo 5 caracteres',
    noticePrivacy = 'Aviso de privacidad',
    phoneNumberError = 'Debes ingresar un numero de 10 digitos',
    phoneVerificationPhaseOne = 'Necesitamos validar tu número para\ncontinuar',
    phoneVerificationPhaseTwo = 'Ingresa tu número a 10 dígitos y te\nenviaremos un código SMS.',
    phoneVerificationTitle = 'VALIDA TU\nCELULAR',
    placeHolderFirstName = 'Nombre (s)',
    placeHolderLastName = 'Apellidos',
    placeHolderPhoneNumber = 'Número de Celular',
    send = 'Enviar',
    signUpSuccessPhraseOne = 'En breve recibirás un correo de\nconfirmación por parte del equipo de\nAtomicLabs.',
    signUpSuccessPhraseTwo = 'Recuerda revisar tu bandeja de SPAM\n!Esperamos verte pronto!',
    signUpTitle = 'Queremos saber que eres tú, por favor ingresa los siguientes datos:',
    wantToBePart = '!Quiero ser parte!',
    wantToKnowMore = 'Quiero saber más',
    weWantKnowYou = 'TE QUEREMOS\nCONOCER',
}

export default Strings;
